
@jobSeeker = "job_seeker"
@employer = "employer"
@serdar20_job_seeker_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsIm5hbWUiOiJzZXJkYXIyMCIsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzUwNzQ5MTAwfQ.oK0uyR0cVkEOjHWWleSUQ9bBeY1cbkg2hRvo-l5aVJo
@serdar23_employer_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsIm5hbWUiOiJzZXJkYXIyMyIsInJvbGUiOiJlbXBsb3llciIsImlhdCI6MTc1MDc0Nzc2NX0.Kn5Hjsaz5Cffyjp3druaJiqGJPirPze5TntKLI3cWoc
@serdar24_employer_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsIm5hbWUiOiJzZXJkYXIyNCIsInJvbGUiOiJlbXBsb3llciIsImlhdCI6MTc1MDg1NTk5NX0.jk3igcBeCj9h7SFeQOIeUqfnlWMLK6fL6VwPn03TSNU

@serdar25_job_seeker_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsIm5hbWUiOiJzZXJkYXIyNSIsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzUwNzUwMzE5fQ.MAjOTK6KXq80iNzfy9uS5Pqnq7sBbw_U6okRKiwaF08
@serdar27_job_seeker_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsIm5hbWUiOiJzZXJkYXIyNyIsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzUwNzUwNDAyfQ.bR1-aEVXqrGZKhyN5QyLy5pT-D0q_omkcDtZWlu9nQs
@serdar28_job_seeker_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsIm5hbWUiOiJzZXJkYXIyOCIsInJvbGUiOiJqb2Jfc2Vla2VyIiwiaWF0IjoxNzUwODI4NzAxfQ.ACjTMxpmP105e-K-FDrEsZio5dHS7JR0I_w7Lb9ssfY
@ADMIN1_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsIm5hbWUiOiJBRE1JTjEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTA4Mzc2MDR9.c4P088P7sWo7CfQtK6AmoOuw5_UqjPbF5psGzdy9ycM
@ADMIN2_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzYsIm5hbWUiOiJBRE1JTjIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTA5MjUwMTB9.pJEkj6-dJqBNZGA2kSCJyzr_Gl-4dTAp5WKkYHS6p1U


##############################################
############### SIGN UP/ LOGIN ###############
##############################################
POST {{baseUrlAUTH}}/auth/api/signup
Content-Type: application/json

{
    "username": "ADMIN2",
    "password": "121212121"
}

//✅username unique
###

POST http://localhost:3000/auth/api/login
Content-Type: application/json

{
  "username": "Orazmyradowa123",
  "password": "atqD5kCabehdn4g"
}

//✅login
############################################
############# EMPLOYER ACTIONS #############
############################################


POST {{baseUrlSERVER}}/jobs/api/employer/create-job
Content-Type: application/json
Authorization: Bearer {{serdar24_employer_token}}

{
    "title": "5555445",
    "description": "description",
    "company": "company",
    "location": "location",
    "category": "category",
    "salary_range": "salary_range",
    "employment_type": "employment_type",
    "is_active": true
}

//job döretýär;
//✅
//✅meňzeş title we description bolsa döredenok
//✅employer job goşýar
//✅job_seeker goşup bilenok :'Access denied. Only employers can create jobs'
###

GET {{baseUrlSERVER}}/jobs/api/employer/jobs?title=back
Content-Type: application/json
Authorization: Bearer {{serdar23_employer_token}}

//✅employer öz job-laryny görýär;
//spesifik employer-iň job-laryny getirip  berýär  
//✅-req.body-ny boş edip ugratmaly! -buny çözmesegä bolanok
//✅-serdar21 employer üçin job ýok diýip görkezýär
//✅-employer bolsa näme!
//✅-access token ugratmasa näme?-şu wagtlykça bulary tapman diňeje birinjini düzedäýinmi?
//✅

//✅filter-ýöne nähili test etmeli!
###

PUT {{baseUrlSERVER}}/jobs/api/employer/update-job/432
Content-Type: application/json
Authorization: Bearer {{serdar23_employer_token}}

{
    "title": "frontend5",
    "description": "description",
    "company": "company",
    "location": "location",
    "category": "category",
    "salary_range": "salary_range",
    "employment_type": "employment_type",
    "is_active": true
}
 
//✅job update edýär;
//

###

DELETE {{baseUrlSERVER}}/jobs/api/employer/delete-job/432
Content-Type: application/json
Authorization: Bearer {{serdar23_employer_token}}

//✅job delete edýär;-egerde favorite edilen bolsa düýbünden pozmak nädogry-favorite-de eýýäm ol maglumat ulanylýär we .. şonuň üçin  is_active=false etmeli

###
GET {{baseUrlSERVER}}/jobs/api/employer/applyed-users/433
Authorization: Bearer {{serdar23_employer_token}}
//✅job_seeker-leri görüp bilýär
//✅-pagination
//✅sortlamak wagt goşmalymyka onda?-soňky apply edenler diýip
//✅page=2✅

//serdar7 job goşmaly soňra şol işe ikisi apply etmelimi?



#############################################
############# jobSeeker ACTIONS #############
#############################################
GET {{baseUrlSERVER}}/jobs/api/job-seeker/jobs?page=2
//✅job-seeker  job-lary görýär;
//✅pagination
//✅filter
//✅page=2✅


###
GET {{baseUrlSERVER}}/jobs/api/job-seeker/jobs/432
//✅220 id-li işi görüp bilýär
###
POST {{baseUrlSERVER}}/jobs/api/job-seeker/applying-job/428
Content-Type: application/json
Authorization: Bearer {{serdar25_job_seeker_token}}

//✅ apply etýär :220 id-li job-y apply etdi!
//✅ user şol bir işe kän gezek apply etmeli dälmi?
//job id boýunça employer-i tutmakçy!

###
GET {{baseUrlSERVER}}/jobs/api/job-seeker/get-all-applyed-jobs
Authorization: Bearer {{serdar27_job_seeker_token}}

//✅user ähli apply eden işlerini görüp bilýär
//✅pagination
//✅filter

###
DELETE {{baseUrlSERVER}}/jobs/api/job-seeker/delete-applyed-job/428
Content-Type: application/json
Authorization: Bearer {{serdar25_job_seeker_token}}

//✅apply edilen işi delete edip bilýärmi?


#############################################
################### ADMIN ###################
#############################################

 GET {{baseUrlSERVER}}/admin/api/jobs
 Authorization: Bearer {{ADMIN1_TOKEN}}


###
 DELETE {{baseUrlSERVER}}/admin/api/job/486
 Authorization: Bearer {{ADMIN1_TOKEN}}

 
###

 GET {{baseUrlSERVER}}/admin/api/users?role=employer
 Authorization: Bearer {{ADMIN1_TOKEN}}

###
 DELETE {{baseUrlSERVER}}/admin/api/user/30
 Authorization: Bearer {{ADMIN1_TOKEN}}

###
 GET {{baseUrlSERVER}}/admin/api/fav-jobs
 Authorization: Bearer {{ADMIN1_TOKEN}}

###




#############################################
#################### END ####################
#############################################

//❌delete edilen employer-leriň job-lary job_seeker-lere görünmeli däl!

















################################################################################################
########################################## E-COMMERCE ##########################################
################################################################################################
# @serdar1_user_token

//❌-token

#############################################
################### ADMIN ###################
#############################################

########################
###### categories ######
########################
GET {{baseUrlSERVER}}/admin/api/categories
###
POST {{baseUrlSERVER}}/admin/api/create-category
# Authorization: Bearer 
Content-Type: application/json

{
    "name":"süýt önümleri"
}

###
PUT {{baseUrlSERVER}}/admin/api/update-category/3
# Authorization: Bearer 
Content-Type: application/json

{
    "name":"cars"
}

###
DELETE {{baseUrlSERVER}}/admin/api/delete-category/1

########################
######### user #########
########################

# PUT {{baseUrlSERVER}}/admin/api/update-user/1
# Content-Type: application/json

# {
#     "name":"",
#     "password":"12121212"    
# }
###
DELETE {{baseUrlSERVER}}/admin/api/delete-user/4
# Authorization: Bearer 

###
GET {{baseUrlSERVER}}/admin/api/users
###
POST  {{baseUrlSERVER}}/admin/api/create-user
Content-Type: application/json

{
    "username": "serdar5",
    "password": "121212121"
}


#########################
######## product ########
#########################
POST {{baseUrlSERVER}}/admin/api/create-product
# Authorization: Bearer 
Content-Type: application/json

{
    "name":"name3",
    "description":"description3",
    "stock":4,
    "price":120,
    "category_id":111,
    "main_image":"abc.jpg"
}
###
# POST {{baseUrlSERVER}}/admin/api/add-product-images
# Authorization: Bearer 
# Content-Type: application/json

###
PUT {{baseUrlSERVER}}/admin/api/update-product/12
# Authorization: Bearer 
Content-Type: application/json

{
    "name":"name2",
    "description":"description2",
    "stock":4,
    "price":120,
    "category_id":6,
    "main_image":"abc.jpg"
}

###
GET {{baseUrlSERVER}}/admin/api/get-products?limit=12
###
DELETE {{baseUrlSERVER}}/admin/api/delete-product/12

##########################
######### images #########
##########################

POST {{baseUrlSERVER}}/admin/api/add-image
Content-Type: application/json

{
    "product_id":,
    "img_path":""
}

###
GET http://localhost:3000/order_item/order_items.json


